### PR TITLE
Added navbar for smaller devices

### PR DESCRIPTION
**Pull request by RohanJacob23**
Hello @parneetsingh022,

I have added a sidebar using pure CSS and JS for mobile devices. Could you please review it?

### CODE REVIEW

**Review by parneetsingh022 — CHANGES_REQUESTED** [review]
Hello @RohanJacob23
I'm glad you worked on it, but there some problems that needs to be fixed:

- In the following code you are using ***document.getElementById*** and **addEventListener** but it is not the ideal way of doing things in reactjs or nextjs. To address it you can create separate functions for both of your mouse click events and then put them in an **onClick={() => func_name()}** attribute. Furthermore, you can store Other required properties in react useState hook instead of using **document.getElementById**.
```javascript
  // needed to use useEffect to access the html DOM
  useEffect(() => {
    // getting the DOM elements
    const overlayBg = document.getElementById("overlay");
    const sidebar = document.getElementById("sidebar");
    const menuOpen = document.getElementById("menu");
    const menuClose = document.getElementById("close-icon");

    const { pathname } = useRouter();  // pathname is used to check whether the current link is active
    // event listener to open the menu
    menuOpen.addEventListener("click", () => {
      sidebar.style.transform = "translateX(0)";
      overlayBg.style.display = "block";
    });

    // event listener to close the menu
    menuClose.addEventListener("click", () => {
      sidebar.style.transform = "translateX(20rem)";
      overlayBg.style.display = "none";
    });
  }, []);
```

- Secondly, there is a problem in the way the colors are managed, all the color codes are written in global.css (you don't have to import that in CSS file) but in the following CSS code you are writing have colors which are not in globals.css. Try to use utilize colors in global.css if possible, but if you think you need additional colors you can add them in globals.css and then use it. **This is done in this way because later it will be helpful to do dark/light mode toggle**
```css
.right_nav {
    display: flex;
    flex-direction: column;
    position: fixed;
    height: 100%;
    width: 40%;
    top: 0;
    right: 0;
    gap: 0.25rem;
    background: rgb(93, 94, 90);
    background: linear-gradient(
      90deg,
      rgba(47, 47, 47, 1) 0%,
      rgba(33, 37, 41, 1) 100%
    );
    padding: 15px;
    transform: translateX(20rem);
    transition: transform 0.75s ease-in-out;
  }
```
Overall, I liked the implementation of the navbar :)

**Comment by parneetsingh022** [comment]
## There are also some very important issues in the navbar I found!
- When we make the window small, the sidebar appears and closes automatically which is not an ideal behavior.
- When we close the side bar and then make the window bigger nav links do not appear!!

Capture

**Comment by RohanJacob23** [comment]
> Hello @RohanJacob23 I'm glad you worked on it, but there some problems that needs to be fixed:
> 
> * In the following code you are using _**document.getElementById**_ and **addEventListener** but it is not the ideal way of doing things in reactjs or nextjs. To address it you can create separate functions for both of your mouse click events and then put them in an **onClick={() => func_name()}** attribute. Furthermore, you can store Other required properties in react useState hook instead of using **document.getElementById**.
> 
> ```js
>   // needed to use useEffect to access the html DOM
>   useEffect(() => {
>     // getting the DOM elements
>     const overlayBg = document.getElementById("overlay");
>     const sidebar = document.getElementById("sidebar");
>     const menuOpen = document.getElementById("menu");
>     const menuClose = document.getElementById("close-icon");
> 
>     const { pathname } = useRouter();  // pathname is used to check whether the current link is active
>     // event listener to open the menu
>     menuOpen.addEventListener("click", () => {
>       sidebar.style.transform = "translateX(0)";
>       overlayBg.style.display = "block";
>     });
> 
>     // event listener to close the menu
>     menuClose.addEventListener("click", () => {
>       sidebar.style.transform = "translateX(20rem)";
>       overlayBg.style.display = "none";
>     });
>   }, []);
> ```
> 
> * Secondly, there is a problem in the way the colors are managed, all the color codes are written in global.css (you don't have to import that in CSS file) but in the following CSS code you are writing have colors which are not in globals.css. Try to use utilize colors in global.css if possible, but if you think you need additional colors you can add them in globals.css and then use it. **This is done in this way because later it will be helpful to do dark/light mode toggle**
> 
> ```css
> .right_nav {
>     display: flex;
>     flex-direction: column;
>     position: fixed;
>     height: 100%;
>     width: 40%;
>     top: 0;
>     right: 0;
>     gap: 0.25rem;
>     background: rgb(93, 94, 90);
>     background: linear-gradient(
>       90deg,
>       rgba(47, 47, 47, 1) 0%,
>       rgba(33, 37, 41, 1) 100%
>     );
>     padding: 15px;
>     transform: translateX(20rem);
>     transition: transform 0.75s ease-in-out;
>   }
> ```
> 
> Overall, I liked the implementation of the navbar :)

Hello @parneetsingh022,

I have made the changes as per the requirements and implemented them using virtual DOM.

**Comment by parneetsingh022** [comment]
> ## There are also some very important issues in the navbar I found!
> * When we make the window small, the sidebar appears and closes automatically which is not an ideal behavior.
> * When we close the side bar and then make the window bigger nav links do not appear!!
> 
> Capture

@RohanJacob23 
did you address these issues

**Comment by RohanJacob23** [comment]
> ## There are also some very important issues in the navbar I found!
> * When we make the window small, the sidebar appears and closes automatically which is not an ideal behavior.
> * When we close the side bar and then make the window bigger nav links do not appear!!
> 
> Capture

This will only occur when you change the responsive settings directly from your computer. It will not occur when you open it directly from a smaller device.

**Comment by parneetsingh022** [comment]
@RohanJacob23 
That's right but when someone opens it from his computer and makes the window smaller it won't look good.
Kindly check if it could be fixed.
Second one seems to have been fixed..

**Comment by RohanJacob23** [comment]
Okay, I will take a note of it.

**Review by parneetsingh022 — APPROVED** [review]

**Comment by parneetsingh022** [comment]
Looks ok.

**Pull request merged**
